version: '3'

services:

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      example-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./config.monitoring
    networks:
      example-network:
        ipv4_address: 172.16.238.12

  application:
    image: application
    command: uvicorn server:app --host 0.0.0.0 --port 8080 --workers 4
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
    build: ./fastapi_app
    volumes:
      - './fastapi_app:/app'
    ports:
      - 8080:8080
    restart: always
    networks:
      example-network:
        ipv4_address: 172.16.238.10

  web_server:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - application
    depends_on:
      - application
    restart: always
    networks:
      example-network:
        ipv4_address: 172.16.238.13

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
