# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "application"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "application"
    dns_sd_configs:
      - names: ["application"]
        port: 8080
        type: A
        refresh_interval: 5s