version: '3'

services:

  application:
    image: application
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    build: ./sanic_app
    volumes:
      - './sanic_app:/app'
    ports:
      - 8080:8080
    restart: always

  web_server:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    build: ./nginx
    ports:
      - "80:80"
    links:
      - application
    depends_on:
      - application
    restart: always
